# Generated by Django 3.2.5 on 2021-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
