# Generated by Django 3.2.5 on 2021-09-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_rename_userprofile_useraccount'),
        ('checkout', '0002_rename_original_bag_order_original_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='useraccount.useraccount'),
        ),
    ]
